// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform, debugPrint;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web {
    final apiKey = dotenv.env['FIREBASE_WEB_API_KEY'];
    final appId = dotenv.env['FIREBASE_WEB_APP_ID'];
    final messagingSenderId = dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'];
    final projectId = dotenv.env['FIREBASE_WEB_PROJECT_ID'];
    final authDomain = dotenv.env['FIREBASE_WEB_AUTH_DOMAIN'];
    final storageBucket = dotenv.env['FIREBASE_WEB_STORAGE_BUCKET'];
    final measurementId = dotenv.env['FIREBASE_WEB_MEASUREMENT_ID'];

    if (apiKey == null ||
        appId == null ||
        messagingSenderId == null ||
        projectId == null ||
        authDomain == null ||
        storageBucket == null) {
      throw StateError('Missing Firebase Web credentials in .env file.');
    }

    if (projectId != 'chicha123') {
      throw StateError(
        'Invalid Firebase Project ID: $projectId. Expected: chicha123',
      );
    }

    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      authDomain: authDomain,
      storageBucket: storageBucket,
      measurementId: measurementId,
    );
  }

  static FirebaseOptions get windows {
    // Check if Windows specific keys exist, otherwise fall back to Web keys
    final apiKey =
        dotenv.env['FIREBASE_WINDOWS_API_KEY'] ??
        dotenv.env['FIREBASE_WEB_API_KEY'];
    final appId =
        dotenv.env['FIREBASE_WINDOWS_APP_ID'] ??
        dotenv.env['FIREBASE_WEB_APP_ID'];
    final messagingSenderId =
        dotenv.env['FIREBASE_WINDOWS_MESSAGING_SENDER_ID'] ??
        dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'];
    final projectId =
        dotenv.env['FIREBASE_WINDOWS_PROJECT_ID'] ??
        dotenv.env['FIREBASE_WEB_PROJECT_ID'];
    final authDomain =
        dotenv.env['FIREBASE_WINDOWS_AUTH_DOMAIN'] ??
        dotenv.env['FIREBASE_WEB_AUTH_DOMAIN'];
    final storageBucket =
        dotenv.env['FIREBASE_WINDOWS_STORAGE_BUCKET'] ??
        dotenv.env['FIREBASE_WEB_STORAGE_BUCKET'];
    final measurementId =
        dotenv.env['FIREBASE_WINDOWS_MEASUREMENT_ID'] ??
        dotenv.env['FIREBASE_WEB_MEASUREMENT_ID'];

    if (apiKey == null ||
        appId == null ||
        messagingSenderId == null ||
        projectId == null ||
        authDomain == null ||
        storageBucket == null ||
        measurementId == null) {
      throw StateError(
        'Missing Firebase Windows/Web credentials in .env file.',
      );
    }

    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      authDomain: authDomain,
      storageBucket: storageBucket,
      measurementId: measurementId,
    );
  }

  static FirebaseOptions get android {
    final apiKey = dotenv.env['FIREBASE_ANDROID_API_KEY'];
    final appId = dotenv.env['FIREBASE_ANDROID_APP_ID'];
    final messagingSenderId =
        dotenv.env['FIREBASE_ANDROID_MESSAGING_SENDER_ID'];
    final projectId = dotenv.env['FIREBASE_ANDROID_PROJECT_ID'];
    final storageBucket = dotenv.env['FIREBASE_ANDROID_STORAGE_BUCKET'];

    // Throw StateError if credentials are missing (consistent with web/windows)
    if (apiKey == null ||
        appId == null ||
        messagingSenderId == null ||
        projectId == null ||
        storageBucket == null) {
      throw StateError('Missing Firebase Android credentials in .env file.');
    }

    // Validation to ensure projectId matches the intended app
    if (projectId != 'chicha123') {
      throw StateError(
        'Invalid Firebase Project ID: $projectId. Expected: chicha123',
      );
    }

    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      storageBucket: storageBucket,
    );
  }
}
