// Mocks generated by Mockito 5.4.6 from annotations
// in bhashalens_app/test/services/hybrid_router_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bhashalens_app/services/aws_cloud_service.dart' as _i2;
import 'package:connectivity_plus/connectivity_plus.dart' as _i5;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCloudTranslationResult_0 extends _i1.SmartFake
    implements _i2.CloudTranslationResult {
  _FakeCloudTranslationResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCloudGrammarResult_1 extends _i1.SmartFake
    implements _i2.CloudGrammarResult {
  _FakeCloudGrammarResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCloudQAResult_2 extends _i1.SmartFake implements _i2.CloudQAResult {
  _FakeCloudQAResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCloudConversationResult_3 extends _i1.SmartFake
    implements _i2.CloudConversationResult {
  _FakeCloudConversationResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCloudSimplificationResult_4 extends _i1.SmartFake
    implements _i2.CloudSimplificationResult {
  _FakeCloudSimplificationResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCloudOrchestrationResult_5 extends _i1.SmartFake
    implements _i2.CloudOrchestrationResult {
  _FakeCloudOrchestrationResult_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AwsCloudService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAwsCloudService extends _i1.Mock implements _i2.AwsCloudService {
  MockAwsCloudService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<_i2.CloudTranslationResult> translateText({
    required String? sourceText,
    required String? sourceLang,
    required String? targetLang,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #translateText,
          [],
          {
            #sourceText: sourceText,
            #sourceLang: sourceLang,
            #targetLang: targetLang,
            #userId: userId,
          },
        ),
        returnValue: _i3.Future<_i2.CloudTranslationResult>.value(
            _FakeCloudTranslationResult_0(
          this,
          Invocation.method(
            #translateText,
            [],
            {
              #sourceText: sourceText,
              #sourceLang: sourceLang,
              #targetLang: targetLang,
              #userId: userId,
            },
          ),
        )),
      ) as _i3.Future<_i2.CloudTranslationResult>);

  @override
  _i3.Future<_i2.CloudGrammarResult> checkGrammar({
    required String? text,
    required String? language,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkGrammar,
          [],
          {
            #text: text,
            #language: language,
            #userId: userId,
          },
        ),
        returnValue:
            _i3.Future<_i2.CloudGrammarResult>.value(_FakeCloudGrammarResult_1(
          this,
          Invocation.method(
            #checkGrammar,
            [],
            {
              #text: text,
              #language: language,
              #userId: userId,
            },
          ),
        )),
      ) as _i3.Future<_i2.CloudGrammarResult>);

  @override
  _i3.Future<_i2.CloudQAResult> answerQuestion({
    required String? question,
    required String? language,
    String? context,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #answerQuestion,
          [],
          {
            #question: question,
            #language: language,
            #context: context,
            #userId: userId,
          },
        ),
        returnValue: _i3.Future<_i2.CloudQAResult>.value(_FakeCloudQAResult_2(
          this,
          Invocation.method(
            #answerQuestion,
            [],
            {
              #question: question,
              #language: language,
              #context: context,
              #userId: userId,
            },
          ),
        )),
      ) as _i3.Future<_i2.CloudQAResult>);

  @override
  _i3.Future<_i2.CloudConversationResult> practiceConversation({
    required String? userMessage,
    required String? language,
    required List<Map<String, String>>? conversationHistory,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #practiceConversation,
          [],
          {
            #userMessage: userMessage,
            #language: language,
            #conversationHistory: conversationHistory,
            #userId: userId,
          },
        ),
        returnValue: _i3.Future<_i2.CloudConversationResult>.value(
            _FakeCloudConversationResult_3(
          this,
          Invocation.method(
            #practiceConversation,
            [],
            {
              #userMessage: userMessage,
              #language: language,
              #conversationHistory: conversationHistory,
              #userId: userId,
            },
          ),
        )),
      ) as _i3.Future<_i2.CloudConversationResult>);

  @override
  _i3.Future<_i2.CloudSimplificationResult> simplifyText({
    required String? text,
    required String? targetComplexity,
    required String? language,
    bool? includeExplanation = false,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #simplifyText,
          [],
          {
            #text: text,
            #targetComplexity: targetComplexity,
            #language: language,
            #includeExplanation: includeExplanation,
            #userId: userId,
          },
        ),
        returnValue: _i3.Future<_i2.CloudSimplificationResult>.value(
            _FakeCloudSimplificationResult_4(
          this,
          Invocation.method(
            #simplifyText,
            [],
            {
              #text: text,
              #targetComplexity: targetComplexity,
              #language: language,
              #includeExplanation: includeExplanation,
              #userId: userId,
            },
          ),
        )),
      ) as _i3.Future<_i2.CloudSimplificationResult>);

  @override
  _i3.Future<_i2.CloudOrchestrationResult> orchestrate({
    required String? text,
    required String? mode,
    required String? language,
    String? context,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #orchestrate,
          [],
          {
            #text: text,
            #mode: mode,
            #language: language,
            #context: context,
            #userId: userId,
          },
        ),
        returnValue: _i3.Future<_i2.CloudOrchestrationResult>.value(
            _FakeCloudOrchestrationResult_5(
          this,
          Invocation.method(
            #orchestrate,
            [],
            {
              #text: text,
              #mode: mode,
              #language: language,
              #context: context,
              #userId: userId,
            },
          ),
        )),
      ) as _i3.Future<_i2.CloudOrchestrationResult>);

  @override
  _i3.Future<Map<String, dynamic>> explainText({
    required String? text,
    required String? targetLanguage,
    String? sourceLanguage,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #explainText,
          [],
          {
            #text: text,
            #targetLanguage: targetLanguage,
            #sourceLanguage: sourceLanguage,
            #userId: userId,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getBasicGuide(
    String? situation,
    String? language,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBasicGuide,
          [
            situation,
            language,
          ],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<String> startRoleplay(
    String? situation,
    String? goal,
    String? language,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #startRoleplay,
          [
            situation,
            goal,
            language,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #startRoleplay,
            [
              situation,
              goal,
              language,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i5.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i6.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i3.Stream<List<_i6.ConnectivityResult>>.empty(),
      ) as _i3.Stream<List<_i6.ConnectivityResult>>);

  @override
  _i3.Future<List<_i6.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i3.Future<List<_i6.ConnectivityResult>>.value(
            <_i6.ConnectivityResult>[]),
      ) as _i3.Future<List<_i6.ConnectivityResult>>);
}
