# Lambda Layer for shared dependencies and utilities
resource "aws_lambda_layer_version" "shared" {
  filename            = "layers/shared.zip"
  layer_name          = "bhashalens-shared-${var.env}"
  description         = "Shared Python utilities and dependencies for BhashaLens"
  compatible_runtimes = ["python3.11"]
  source_code_hash    = filebase64sha256("layers/shared.zip")

  # Note: The ZIP file should be generated by a CI/CD script before applying this TF configuration.
  # This serves as a placeholder pointing to the expected file.
}
# Example of one Lambda function setup. The others follow the identical pattern.
resource "aws_lambda_function" "translation" {
  filename         = "functions/translation_handler.zip"
  function_name    = "bhashalens-translation-${var.env}"
  role             = var.lambda_execution_role_arn
  handler          = "translation_handler.lambda_handler"
  runtime          = "python3.11"
  timeout          = 30
  memory_size      = 512
  layers           = [aws_lambda_layer_version.shared.arn]
  source_code_hash = filebase64sha256("functions/translation_handler.zip")

  environment {
    variables = {
      TRANSLATION_HISTORY_TABLE = var.translation_history_table
      BEDROCK_MODEL_ID          = var.bedrock_model_id
      # GEMINI_API_KEY will be injected securely from SecretsManager or env wrapper
    }
  }
}
resource "aws_lambda_function" "authorizer" {
  filename         = "functions/authorizer.zip"
  function_name    = "bhashalens-authorizer-${var.env}"
  role             = var.lambda_execution_role_arn
  handler          = "authorizer.lambda_handler"
  runtime          = "python3.11"
  timeout          = 10
  memory_size      = 256
  layers           = [aws_lambda_layer_version.shared.arn]
}

resource "aws_lambda_function" "assistance" {
  filename         = "functions/assistance_handler.zip"
  function_name    = "bhashalens-assistance-${var.env}"
  role             = var.lambda_execution_role_arn
  handler          = "assistance_handler.lambda_handler"
  runtime          = "python3.11"
  timeout          = 30
  memory_size      = 512
  layers           = [aws_lambda_layer_version.shared.arn]

  environment {
    variables = {
      BEDROCK_MODEL_ID = var.bedrock_model_id
    }
  }
}

resource "aws_lambda_function" "simplification" {
  filename         = "functions/simplification_handler.zip"
  function_name    = "bhashalens-simplification-${var.env}"
  role             = var.lambda_execution_role_arn
  handler          = "simplification_handler.lambda_handler"
  runtime          = "python3.11"
  timeout          = 30
  memory_size      = 512
  layers           = [aws_lambda_layer_version.shared.arn]

  environment {
    variables = {
      BEDROCK_MODEL_ID = var.bedrock_model_id
    }
  }
}

resource "aws_lambda_function" "history" {
  filename         = "functions/history_handler.zip"
  function_name    = "bhashalens-history-${var.env}"
  role             = var.lambda_execution_role_arn
  handler          = "history_handler.lambda_handler"
  runtime          = "python3.11"
  timeout          = 15
  memory_size      = 256
  layers           = [aws_lambda_layer_version.shared.arn]

  environment {
    variables = {
      TRANSLATION_HISTORY_TABLE = var.translation_history_table
    }
  }
}

resource "aws_lambda_function" "saved" {
  filename         = "functions/saved_handler.zip"
  function_name    = "bhashalens-saved-${var.env}"
  role             = var.lambda_execution_role_arn
  handler          = "saved_handler.lambda_handler"
  runtime          = "python3.11"
  timeout          = 15
  memory_size      = 256
  layers           = [aws_lambda_layer_version.shared.arn]

  environment {
    variables = {
      SAVED_TRANSLATIONS_TABLE = var.saved_translations_table
    }
  }
}

resource "aws_lambda_function" "preferences" {
  filename         = "functions/preferences_handler.zip"
  function_name    = "bhashalens-preferences-${var.env}"
  role             = var.lambda_execution_role_arn
  handler          = "preferences_handler.lambda_handler"
  runtime          = "python3.11"
  timeout          = 15
  memory_size      = 256
  layers           = [aws_lambda_layer_version.shared.arn]

  environment {
    variables = {
      USER_PREFERENCES_TABLE = var.user_preferences_table
    }
  }
}

resource "aws_lambda_function" "export" {
  filename         = "functions/export_handler.zip"
  function_name    = "bhashalens-export-${var.env}"
  role             = var.lambda_execution_role_arn
  handler          = "export_handler.lambda_handler"
  runtime          = "python3.11"
  timeout          = 45
  memory_size      = 1024
  layers           = [aws_lambda_layer_version.shared.arn]

  environment {
    variables = {
      TRANSLATION_HISTORY_TABLE = var.translation_history_table
      SAVED_TRANSLATIONS_TABLE  = var.saved_translations_table
      EXPORT_BUCKET             = var.export_bucket
    }
  }
}
