import 'dart:convert';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:amplify_api/amplify_api.dart';

class AmplifyDataService {
  bool _isConfigured = false;

  Future<void> configureAmplify(String amplifyOutputsJson) async {
    if (_isConfigured) return;

    try {
      final api = AmplifyAPI();
      
      await Amplify.addPlugin(api);
      
      // The exact initialization depends on amplify_outputs.json
      if (amplifyOutputsJson.isNotEmpty) {
        // await Amplify.configure(amplifyOutputsJson); 
        // Need to pass the content from amplify_outputs.json generated by Amplify Gen 2
      }
      _isConfigured = true;
      safePrint('Amplify Analytics & API successfully configured');
    } on Exception catch (e) {
      safePrint('Error configuring Amplify: $e');
    }
  }

  // Generic function to query GraphQL data in Gen 2 (if models are not generated yet)
  Future<List<Map<String, dynamic>>> queryTable(String document, {Map<String, dynamic>? variables}) async {
    try {
      final request = GraphQLRequest<String>(
        document: document,
        variables: variables ?? const <String, dynamic>{},
      );

      final response = await Amplify.API.query(request: request).response;
      
      if (response.data != null) {
        final Map<String, dynamic> data = jsonDecode(response.data!);
        final key = data.keys.first;
        final list = (data[key]['items'] as List?)?.cast<Map<String, dynamic>>() ?? [];
        return list;
      } else {
        safePrint('GraphQL Query failed: ${response.errors}');
        return [];
      }
    } on ApiException catch (e) {
      safePrint('GraphQL Query Exception: $e');
      return [];
    }
  }

  // Provide high-level wrappers based on models
  Future<List<Map<String, dynamic>>> getTranslationHistory() async {
    const query = '''
      query ListTranslationHistories {
        listTranslationHistories {
          items {
            id
            originalText
            translatedText
            sourceLanguage
            targetLanguage
            timestamp
          }
        }
      }
    ''';
    return await queryTable(query);
  }

  Future<List<Map<String, dynamic>>> getSavedTranslations() async {
    const query = '''
      query ListSavedTranslations {
        listSavedTranslations {
          items {
            id
            phrase
            intent
            translatedPhrase
            timestamp
          }
        }
      }
    ''';
    return await queryTable(query);
  }
  Future<void> deleteSavedTranslation(String id) async {
    const query = '''
      mutation DeleteSavedTranslations(\$id: ID!) {
        deleteSavedTranslations(input: { id: \$id }) {
          id
        }
      }
    ''';
    await queryTable(query, variables: {'id': id});
  }

  Future<void> saveTranslation(Map<String, dynamic> item) async {
    const query = '''
      mutation CreateSavedTranslations(\$phrase: String!, \$translatedPhrase: String!, \$intent: String!, \$timestamp: AWSDateTime!) {
        createSavedTranslations(input: { 
          phrase: \$phrase, 
          translatedPhrase: \$translatedPhrase, 
          intent: \$intent,
          timestamp: \$timestamp
        }) {
          id
        }
      }
    ''';
    // Just a basic map, Gen 2 provides typed models if generated
    await queryTable(query, variables: {
      'phrase': item['originalText'] ?? '',
      'translatedPhrase': item['translatedText'] ?? '',
      'intent': item['category'] ?? 'General',
      'timestamp': DateTime.now().toUtc().toIso8601String(),
    });
  }
}

// Global instance for simple access similar to other services
final amplifyDataService = AmplifyDataService();
